server:
  port: 8102


spring:
  application:
      name: backend
  datasource:
    druid:
#mysql
#      url: jdbc:mysql://192.168.64.130:3306/backend_manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#      username: master
#      password: 123456
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      test-on-borrow: true
#      driver-class-name: com.mysql.jdbc.Driver
#oracle
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@//192.168.64.130:1521/ORCLPDB1
      username: manager
      password: 123456
      validationQuery: select 1 from dual
#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: UTF-8
#      content-type: text/html

mybatis:
    mapper-locations: classpath:mapper/*.xml

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/
